### ISSUE TITLE
User/Survey Data Model 

### ISSUE THREAD

**Issue by GreysonElkins** [michaeljevans/Crate#10]
What will our final user data contain? What does the server respond with on login? How to keep track of surveys

**Comment by sciencefixion** [comment]
I think we decided on 
* users having a style attribute,
* surveys belong to a user,
* and survey results will be stored in the database.

(please correct me if I'm wrong about any of this)

**Comment by GreysonElkins** [comment]
@sciencefixion I think you're right. 
I'm personally a little unclear on how surveys belong to a user if a user doesn't hold the foreign key of its survey.

**Comment by GreysonElkins** [comment]
#33 contains the result of this question!
