### ISSUE TITLE
Set-up Storybook Interface

### ISSUE THREAD

**Issue by GreysonElkins** [michaeljevans/Crate#27]
The front end uses a GUI to interact with rendered components (I believe to work on style.)
To set it up, in the `web` directory, you'll need to 
- [x] run `npm i -D @storybook/addon-actions`
  - It seems this package is missing in the original repo
- [x] run `npm run storybook`
  - this will open storybook in chrome

**Comment by GreysonElkins** [comment]
I'm set up on this! @NakiNorton when you're set with it the issue can be closed!

**Comment by NakiNorton** [comment]
Thanks! I'm all set up now.
