### ISSUE TITLE
Check In 2: Electric Boogaloo! questions

### ISSUE THREAD

**Issue by sciencefixion** [michaeljevans/Crate#31]
Questions go here.

**Comment by GreysonElkins** [comment]
- [ ] (in `src/modules/crate/items.js` and `src/modules/subscription/api`
Does the create subscription function actually talk to dispatch? It does not seem to affect state, but it is followed by `.then` statements with functions which are mapped to dispatch. (create is also matched to dispatch, but does not have an action type.)
