### ISSUE TITLE
User stories 

### ISSUE THREAD

**Issue by NakiNorton** [michaeljevans/Crate#32]
Instructions: Create detailed user stories and chores defining implementation details for the functionality you will add

**Comment by GreysonElkins** [comment]
- If I click subscription for the first time I will be given a survey where I can make choices about my style
- Each question lets me pick an image that best represents my personal style
- I cannot submit a survey without finishing it 
- Once I submit a survey I'm taken to my subscriptions page, and the subscription I've chosen is displayed - there's a heading which displays my style. The profile page also displays my chosen style.
