### ISSUE TITLE
Survey Objects

### ISSUE THREAD

**Issue by GreysonElkins** [michaeljevans/Crate#33]
```
 {
  id: 1, 
  // belongs to relationship
  surveyContents: [{
  // provided by the FE
      question: 'Are you more casual or formal',
      images: [{src: 'path' value: 'TBD'}, {src: 'path' value: 'TBD'}, {src: 'path' value: 'TBD'}],
      answer: 'valueOfSelection'
    }, {
      question: 'Are you more casual or formal',
      images: [{src: 'path' value: 'TBD'}, {src: 'path' value: 'TBD'}, {src: 'path' value: 'TBD'}],
      answer: 'valueOfSelection'
    }
    ] 
  },
  result: getStyle(surveyContents) //also stored in user
}
```

**Comment by NakiNorton** [comment]
Notes for structure/flow of the style survey feature:
- Template for survey will live on front end
- Back end will add new `style` attribute to user object (?) and set default value (null)
- Images for survey will live on front end
- When user submits survey, the surveyContents will get sent to the back end
- Back end will take survey results, do some stuff, and assign a style value (string) to the users 'style' attribute
- Display the users style result on the Subscriptions page (where they'll be redirected to once they submit survey)
_- Possible addition: Front end can display the users style on their profile page___
- Storing the survey so the user can access the survey and change their responses (backend) ....

**Comment by GreysonElkins** [comment]
userId should be included here.

**Comment by GreysonElkins** [comment]
I think we should add a `description` value to each `answer` object for the sake of alt text
