### ISSUE TITLE
Make list of files that will need to be updated to add style survey feature (Deliverable(?) for check in 2)

### ISSUE THREAD

**Issue by NakiNorton** [michaeljevans/Crate#38]
**Instructions:** Make a list of the specific files of code that will need to be updated in order to add the additional features outlined in your track

**Back end files:**
- 'code/api/src/seeders/1-user.js' 
_Is this where we give the user object a new property called `style` and give it a default value of `null` to being with?_
Yes; but this will only affect the data the database contains. We'll also need to create a new migration for surveys, and add a style attribute to the user migration

- 'code/api/src/modules/user/model.js'
_Need to add `style` property and `type` to User object_

- 'code/api/src/modules/
_A directory and files for style surveys_

**Front end files:**
- 'code/web/src/modules/user/api/actions.js'
This is where the axios.post request for the users details happens. Need to add `style` (or whatever we want to call this key) into the fields list so we get that data back in response: 
i.e. `fields: ['user {name, email, role, style}', 'token']`

- ‘code/web/src/modules/crate/Item.js’ 
_This is where the Subscribe button is rendered. Need to add logic that checks if user has already taken survey and then redirect user on button click based on that._

- 'code/web/src/modules/user/Subscriptions.js'
_This is the users Subscriptions page. Add users style to display (if they've taken survey)_ 

- 'code/web/src/modules/user/Profile.js'
_This is the users profile. Add users style to display (if they've taken survey)._

- `/style-preferences`
_Not sure where the component will live, but we'll need to create a route for the survey as well as a component_

**Comment by GreysonElkins** [comment]
thanks for starting this Steph! is this part of our check-in deliverables? If so I missed it and hop online in a bit to beef this up a bit.

**Comment by NakiNorton** [comment]
Yeah I missed it too,  it's part of the code annotation instructions:

1. Create a branch called code-annotations-<your name>
2. Each team member will submit their own branch
3. **Make a list of the specific files of code that will need to be updated in order to add the additional features outlined in your track**
4. For each file, walk through the code and add a comment above each line/block that describes what that code is doing.
5. Submit a link to your branch here

**Comment by NakiNorton** [comment]
So I obviously didn't follow this structure to write my annotations. Mine are a little less organized..

We might not need to hand this in, but I think it'll be helpful for when we need to implement our feature anyway

**Comment by GreysonElkins** [comment]
@NakiNorton for sure! I added a few things for both BE and FE. Hopefully there's enough here to get started!
