### ISSUE TITLE
User Story 2: Style Survey Page

### ISSUE THREAD

**Issue by sciencefixion** [michaeljevans/Crate#39]
As a user 
when I visit /style-preferences. 
I am presented with a style survey that consists of a series of categories such as tops, bottoms, dresses, shoes, accessories, etc. 
For each category I am given several images to choose from with instructions to choose the images that best reflects my style.
After I have chosen the images from each category I am given a summary of my style such as ‘classic but edgy’.

Sad path: I cannot submit a survey without finishing it.

**Comment by GreysonElkins** [comment]
I've begun outlining the Survey component on the `feature/ge-survey-component` (#50).
Hit a blocker which I believe is due to React needing images to be imported a certain way, but haven't found any evidence of that being done elsewhere in the project.
