### ISSUE TITLE
Testing - FE User actions and reducers 

### ISSUE THREAD

**Issue by NakiNorton** [michaeljevans/Crate#49]
Testing existing code to set ourselves up for TDD 

- [x] Install tools for Redux testing
- [x] Setup and pass tests for the actions.js in '/web/src/modules/user'
- [x] Setup and pass tests for the state.js in '/web/src/modules/user'

**Comment by NakiNorton** [comment]
@GreysonElkins I was able to get the testing setup. I was missing jest! These are the dependencies I installed:

**1.** Install jest:
`npm install --save-dev jest`
**1.a** Then copy these lines into scripts (package.json):
```
   "test": "jest",
   "test:watch": "npm test -- --watch"
```
_note: `npm run test:watch` to test on every file change._

**2.** Install React Testing Library:
`npm install @testing-library/react@latest`

**3.** Install jest-DOM
`npm i -D @testing-library/jest-dom`

**4.** Install latest version of jest env
`npm install --save-dev jest-environment-jsdom-sixteen`

**Using Redux:**

**4.** Install mock store
`npm i redux-mock-store`

Others for Redux (not sure if we'll need them):

- npm install @reduxjs/toolkit

**Comment by GreysonElkins** [comment]
@NakiNorton thanks for typing this up! Super helpful
